# Generated by Django 3.2.9 on 2021-12-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
            ],
        ),
    ]
