# Generated by Django 3.2.9 on 2021-12-12 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 12, 12, 17, 36, 53, 989182, tzinfo=utc), upload_to='', verbose_name='images/'),
            preserve_default=False,
        ),
    ]
