# Generated by Django 3.2.9 on 2021-12-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211214_0142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fun_Events',
            new_name='Fun_Event',
        ),
    ]
