# Generated by Django 3.2.9 on 2021-12-15 14:24

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_fun_events_fun_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='au_me',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='AU_ME/images'),
        ),
        migrations.AlterField(
            model_name='civil',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Civil/images'),
        ),
        migrations.AlterField(
            model_name='cs_it',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='CS_IT/images'),
        ),
        migrations.AlterField(
            model_name='ele_ec_ic',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Ele_Ec_Ic/images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='event/images'),
        ),
        migrations.AlterField(
            model_name='fun_event',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Fun_Events/images'),
        ),
    ]
