# Generated by Django 3.2.9 on 2021-12-16 18:20

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211215_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Non_Technical/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Seminar/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Technical/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Workshop/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AU_ME',
        ),
        migrations.DeleteModel(
            name='Civil',
        ),
        migrations.DeleteModel(
            name='CS_IT',
        ),
        migrations.DeleteModel(
            name='Ele_Ec_Ic',
        ),
    ]
