# Generated by Django 3.2.9 on 2021-12-31 17:02

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211216_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Auto/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('rounds', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Chemical/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('rounds', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Civil/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('rounds', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Computer/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('rounds', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Electrical/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('rounds', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='Quiz/images')),
                ('short_dec', models.CharField(max_length=200)),
                ('long_dec', models.CharField(max_length=500)),
                ('rule', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('rounds', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='rounds',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fun_event',
            name='rounds',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='non_technical',
            name='rounds',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seminar',
            name='rounds',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='technical',
            name='rounds',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='workshop',
            name='rounds',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
